//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPF.FFTools.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staffID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string psentence { get; set; }
        public string DOB { get; set; }
        public string address { get; set; }
        public string suburb { get; set; }
        public string postcode { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public Nullable<bool> companyphone { get; set; }
        public string phoneNo { get; set; }
        public string mobNo { get; set; }
        public string hkNo { get; set; }
        public string extensionNo { get; set; }
        public string directNo { get; set; }
        public string faxNo { get; set; }
        public string email { get; set; }
        public Nullable<int> departID { get; set; }
        public string location { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string staffposition { get; set; }
        public string sortcode { get; set; }
        public string salesNo { get; set; }
        public string BDCNo { get; set; }
        public string jobtype { get; set; }
        public Nullable<float> payrate { get; set; }
        public string signon { get; set; }
        public string kitchenduty { get; set; }
        public string jobdescription { get; set; }
        public string interest { get; set; }
        public string photo { get; set; }
        public string status { get; set; }
        public string psallocate { get; set; }
        public string quotpermission { get; set; }
        public Nullable<int> groupnumber { get; set; }
        public Nullable<int> plGroupID { get; set; }
        public string contactperson { get; set; }
        public string contactphone { get; set; }
        public Nullable<int> alapproval { get; set; }
        public string manager { get; set; }
        public string almngr { get; set; }
        public string alaccrued { get; set; }
        public string stafflisting { get; set; }
        public Nullable<int> companyid { get; set; }
        public string skype { get; set; }
        public Nullable<int> admin { get; set; }
        public string roll { get; set; }
        public Nullable<System.DateTime> StartDateLSL { get; set; }
        public string passCode { get; set; }
        public Nullable<bool> passCodeAccess { get; set; }
        public Nullable<bool> isStationLoginAccount { get; set; }
    }
}
